import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import {
  FileText,
  Award,
  Users,
  Zap,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  Menu,
  X,
  GraduationCap,
  Mail,
  MapPin,
  BookOpen,
  MessageSquare,
  Target,
} from "lucide-react";

const NAV_LINKS = ["Features", "About", "FAQ"];

const FEATURES = [
  {
    icon: FileText,
    title: "Question Papers",
    desc: "Browse previous year exam papers filtered by branch, semester, and subject. Download any paper instantly as PDF.",
  },
  {
    icon: Award,
    title: "Placement Records",
    desc: "Real CTC data, eligibility criteria, required skills, and actual interview questions from campus drives — like Glassdoor for college placements.",
  },
  {
    icon: MessageSquare,
    title: "Community",
    desc: "Ask doubts, share resources, post achievements, and discuss projects with batchmates and seniors — filtered by your year and branch.",
  },
  {
    icon: Zap,
    title: "AI Recommendations",
    desc: "Get a personalized learning path, trending skills to master, and project ideas generated by AI based on your goals and skills.",
  },
  {
    icon: Target,
    title: "Smart Profile",
    desc: "Set your career goal, add skills and interests, and track your profile completeness to unlock fully personalized guidance.",
  },
  {
    icon: BookOpen,
    title: "Resource Hub",
    desc: "All academic resources in one place — no more hunting across WhatsApp groups, drives, and telegram channels.",
  },
];

const FAQS = [
  {
    q: "What is EduHub?",
    a: "EduHub is a platform built for engineering students — it brings together previous year question papers, campus placement records with real interview questions, a peer community, and AI-powered recommendations all in one place.",
  },
  {
    q: "How do I access question papers?",
    a: "Create a free account, go to the Question Papers section, and filter by branch, semester, or subject. Every paper is downloadable as a PDF.",
  },
  {
    q: "What placement data is available?",
    a: "Each placement record shows the company, CTC, number of students placed, eligibility criteria, required skills, and the actual interview questions asked — submitted by seniors who went through the process.",
  },
  {
    q: "Is EduHub free?",
    a: "Yes, completely free for all students. Our goal is to make quality academic resources accessible to everyone.",
  },
  {
    q: "How does the AI recommendation work?",
    a: "Once your profile is complete with skills, interests, and career goals, EduHub generates a three-phase learning path with trending skills, project ideas, curated resources, and career insights tailored specifically to you.",
  },
];

export default function Home() {
  const [navOpen, setNavOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [openFaq, setOpenFaq] = useState(null);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 40);
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const scrollTo = (id) => {
    document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
    setNavOpen(false);
  };

  return (
    <div
      className="min-h-screen bg-[#080d16] text-white overflow-x-hidden"
      style={{ fontFamily: "'Roboto Condensed', sans-serif" }}
    >
      {/* ── Navbar ── */}
      <nav
        className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
          scrolled ? "bg-[#080d16]/95 backdrop-blur-md border-b border-white/5" : "bg-transparent"
        }`}
      >
        <div className="max-w-6xl mx-auto px-5 h-16 flex items-center justify-between">
          {/* Logo */}
          <Link to="/" className="flex items-center gap-2 font-bold text-xl tracking-tight">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
              <GraduationCap className="w-5 h-5 text-white" />
            </div>
            <span>Edu<span className="text-blue-400">Hub</span></span>
          </Link>

          {/* Desktop nav */}
          <div className="hidden md:flex items-center gap-8 text-sm font-medium text-white/60">
            {NAV_LINKS.map((l) => (
              <button
                key={l}
                onClick={() => scrollTo(l.toLowerCase())}
                className="hover:text-white transition-colors"
              >
                {l}
              </button>
            ))}
          </div>

          {/* Desktop CTA */}
          <div className="hidden md:flex items-center gap-3">
            <Link
              to="/login"
              className="text-sm font-medium text-white/70 hover:text-white transition-colors px-4 py-2"
            >
              Sign In
            </Link>
            <Link
              to="/register"
              className="flex items-center gap-1.5 px-5 py-2 rounded-full bg-blue-600 hover:bg-blue-500 text-white text-sm font-semibold transition-colors"
            >
              Get Started <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          </div>

          {/* Mobile toggle */}
          <button onClick={() => setNavOpen(!navOpen)} className="md:hidden p-2 text-white/70 hover:text-white">
            {navOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
          </button>
        </div>

        {/* Mobile menu */}
        {navOpen && (
          <div className="md:hidden bg-[#0d1420] border-t border-white/5 px-5 py-4 space-y-3">
            {NAV_LINKS.map((l) => (
              <button
                key={l}
                onClick={() => scrollTo(l.toLowerCase())}
                className="block w-full text-left text-sm font-medium text-white/60 hover:text-white py-2 transition-colors"
              >
                {l}
              </button>
            ))}
            <div className="pt-2 flex flex-col gap-2">
              <Link to="/login" className="w-full text-center py-2.5 rounded-full border border-white/20 text-sm font-medium text-white/70 hover:text-white transition-colors">
                Sign In
              </Link>
              <Link to="/register" className="w-full text-center py-2.5 rounded-full bg-blue-600 hover:bg-blue-500 text-sm font-semibold transition-colors">
                Get Started
              </Link>
            </div>
          </div>
        )}
      </nav>

      {/* ── Hero ── */}
      <section
        className="relative min-h-screen flex items-center pt-16 bg-[#080d16]"
        style={{
          backgroundImage: "url('/hero-earth.jpg')",
          backgroundSize: "cover",
          backgroundPosition: "center bottom",
          backgroundRepeat: "no-repeat",
        }}
      >
        {/* Dark overlay so text is readable over the image */}
        <div className="absolute inset-0 bg-gradient-to-b from-[#080d16]/80 via-[#080d16]/50 to-[#080d16]" />
        {/* Side fade — keeps left text area more legible */}
        <div className="absolute inset-0 bg-gradient-to-r from-[#080d16]/90 via-[#080d16]/30 to-transparent" />

        <div className="relative z-10 max-w-6xl mx-auto px-5 py-8 sm:py-10">
          <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-white/10 text-white/50 text-xs font-medium mb-6 tracking-wider uppercase">
            Built for Engineering Students
          </span>

          <h1 className="text-3xl sm:text-5xl lg:text-6xl font-bold italic leading-[1.05] tracking-tight mb-6 max-w-3xl">
            Your College, <span className="text-blue-400">All in One</span> Place.
          </h1>

          <p className="text-white/50 font-normal text-base sm:text-lg leading-relaxed mb-8 max-w-lg">
            Question papers, placement records, peer community, and AI-powered
            learning paths — everything you need to get through college and land your dream role.
          </p>

          <div className="flex flex-wrap gap-3">
            <Link
              to="/register"
              className="flex items-center gap-2 px-7 py-3 rounded-full bg-blue-600 hover:bg-blue-500 text-white font-semibold transition-colors text-sm"
            >
              Start for Free <ArrowRight className="w-4 h-4" />
            </Link>
            <button
              onClick={() => scrollTo("features")}
              className="flex items-center gap-2 px-7 py-3 rounded-full border border-white/20 text-white/70 hover:text-white hover:border-white/40 font-medium transition-colors text-sm backdrop-blur-sm"
            >
              See Features
            </button>
          </div>

          {/* Stats row */}
          <div className="flex flex-wrap gap-10 mt-8 pt-6 border-t border-white/10">
            {[
              { n: "1000+", l: "Question Papers" },
              { n: "50+", l: "Companies" },
              { n: "500+", l: "Students" },
            ].map(({ n, l }) => (
              <div key={l}>
                <p className="text-2xl font-bold italic text-white">{n}</p>
                <p className="text-xs text-white/40 uppercase tracking-wide mt-0.5">{l}</p>
              </div>
            ))}
          </div>
        </div>

      </section>

      {/* ── Features ── */}
      <section id="features" className="py-16 bg-[#0a0f1a]">
        <div className="max-w-6xl mx-auto px-5">
          <div className="mb-10">
            <span className="text-xs text-blue-400 font-semibold uppercase tracking-widest">Features</span>
            <h2 className="text-4xl sm:text-5xl font-bold italic mt-2 leading-tight">
              Everything you need.<br />
              <span className="text-white/30">Nothing you don't.</span>
            </h2>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {FEATURES.map(({ icon: Icon, title, desc }) => (
              <div
                key={title}
                className="bg-[#0d1420] border border-white/5 rounded-2xl p-7 hover:border-blue-500/30 hover:bg-[#0e1828] hover:-translate-y-1 transition-all duration-200 group"
              >
                <div className="w-10 h-10 rounded-xl bg-blue-600/10 border border-blue-500/20 flex items-center justify-center mb-5 group-hover:bg-blue-600/20 group-hover:border-blue-500/40 transition-colors">
                  <Icon className="w-5 h-5 text-blue-400" />
                </div>
                <h3 className="text-lg font-bold italic mb-2 text-white">{title}</h3>
                <p className="text-sm font-normal text-white/40 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── About ── */}
      <section id="about" className="py-16 bg-[#080d16]">
        <div className="max-w-6xl mx-auto px-5 grid lg:grid-cols-2 gap-16 items-center">
          <div>
            <span className="text-xs text-blue-400 font-semibold uppercase tracking-widest">About</span>
            <h2 className="text-4xl sm:text-5xl font-bold italic mt-2 mb-6 leading-tight">
              Built by students,<br />for students.
            </h2>
            <p className="text-white/50 leading-relaxed mb-5">
              EduHub started as a simple idea — stop hunting for question papers across
              WhatsApp groups and Google Drives. It grew into a full academic platform
              covering placements, community discussions, and AI-powered career guidance.
            </p>
            <p className="text-white/50 leading-relaxed mb-8">
              Everything on EduHub is contributed by students and verified for accuracy.
              It's free, always. Our mission is to make every student's college journey
              less stressful and more informed.
            </p>
            <div className="space-y-3">
              {[
                "Free access — no paywalls, no subscriptions",
                "Real interview questions from actual campus drives",
                "AI learning paths based on your goals",
                "Peer community for doubts, resources, and projects",
              ].map((item) => (
                <div key={item} className="flex items-start gap-2.5 text-sm text-white/60">
                  <span className="w-1.5 h-1.5 rounded-full bg-blue-400 mt-1.5 flex-shrink-0" />
                  {item}
                </div>
              ))}
            </div>
            <Link
              to="/register"
              className="inline-flex items-center gap-2 mt-8 px-7 py-3 rounded-full bg-blue-600 hover:bg-blue-500 text-white font-semibold transition-colors text-sm"
            >
              Join EduHub <ArrowRight className="w-4 h-4" />
            </Link>
          </div>

          {/* Right — grid cards */}
          <div className="grid grid-cols-2 gap-3">
            {[
              { icon: FileText, label: "Papers", value: "1000+" },
              { icon: Award, label: "Companies", value: "50+" },
              { icon: Users, label: "Students", value: "500+" },
              { icon: Zap, label: "AI Paths", value: "Instant" },
            ].map(({ icon: Icon, label, value }) => (
              <div
                key={label}
                className="bg-[#0d1420] border border-white/5 rounded-2xl p-6 flex flex-col gap-3"
              >
                <Icon className="w-6 h-6 text-blue-400" />
                <p className="text-2xl font-bold italic text-white">{value}</p>
                <p className="text-xs text-white/40 uppercase tracking-wide">{label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section id="faq" className="py-16 bg-[#0a0f1a]">
        <div className="max-w-2xl mx-auto px-5">
          <div className="mb-8">
            <span className="text-xs text-blue-400 font-semibold uppercase tracking-widest">FAQ</span>
            <h2 className="text-4xl sm:text-5xl font-bold italic mt-2">Questions?</h2>
          </div>

          <div className="space-y-1">
            {FAQS.map((faq, i) => (
              <div key={i} className="border-b border-white/5">
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex items-center justify-between py-5 text-left text-white/80 hover:text-white font-medium text-sm transition-colors gap-4"
                >
                  <span>{faq.q}</span>
                  {openFaq === i
                    ? <ChevronUp className="w-4 h-4 flex-shrink-0 text-blue-400" />
                    : <ChevronDown className="w-4 h-4 flex-shrink-0 text-white/30" />
                  }
                </button>
                {openFaq === i && (
                  <p className="pb-5 text-sm text-white/40 leading-relaxed">{faq.a}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA Banner ── */}
      <section className="py-14 bg-[#080d16]">
        <div className="max-w-3xl mx-auto px-5 text-center">
          <h2 className="text-4xl sm:text-5xl font-bold italic mb-4">
            Ready to get started?
          </h2>
          <p className="text-white/40 font-normal mb-8 text-lg">
            Join hundreds of students already using EduHub to study smarter and prepare for placements.
          </p>
          <Link
            to="/register"
            className="inline-flex items-center gap-2 px-8 py-3.5 rounded-full bg-blue-600 hover:bg-blue-500 text-white font-semibold transition-colors"
          >
            Create Free Account <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="border-t border-white/5 bg-[#080d16]">
        <div className="max-w-6xl mx-auto px-5 py-10 flex flex-col md:flex-row items-start justify-between gap-8">
          {/* Brand */}
          <div>
            <Link to="/" className="flex items-center gap-2 font-bold text-lg mb-3">
              <div className="w-7 h-7 bg-blue-600 rounded-md flex items-center justify-center">
                <GraduationCap className="w-4 h-4 text-white" />
              </div>
              EduHub
            </Link>
            <p className="text-sm text-white/30 max-w-xs leading-relaxed">
              Academic resources for engineering students — question papers, placements, community, and AI guidance.
            </p>
          </div>

          {/* Nav */}
          <div className="flex flex-col gap-2 text-sm text-white/40">
            <p className="text-white/20 font-semibold uppercase tracking-widest text-xs mb-1">Navigate</p>
            {NAV_LINKS.map((l) => (
              <button key={l} onClick={() => scrollTo(l.toLowerCase())} className="text-left hover:text-white transition-colors">
                {l}
              </button>
            ))}
            <Link to="/login" className="hover:text-white transition-colors">Sign In</Link>
            <Link to="/register" className="hover:text-white transition-colors">Register</Link>
          </div>

          {/* Contact */}
          <div className="flex flex-col gap-2 text-sm text-white/40">
            <p className="text-white/20 font-semibold uppercase tracking-widest text-xs mb-1">Contact</p>
            <span className="flex items-center gap-2"><Mail className="w-3.5 h-3.5" /> support@eduhub.com</span>
            <span className="flex items-center gap-2"><MapPin className="w-3.5 h-3.5" /> Bhubaneswar, Odisha</span>
          </div>
        </div>

        <div className="border-t border-white/5">
          <div className="max-w-6xl mx-auto px-5 py-4 flex flex-col sm:flex-row items-center justify-between gap-2 text-xs text-white/20">
            <span>&copy; {new Date().getFullYear()} EduHub. All rights reserved.</span>
            <div className="flex gap-5">
              <Link to="/" className="hover:text-white/50 transition-colors">Privacy</Link>
              <Link to="/" className="hover:text-white/50 transition-colors">Terms</Link>
            </div>
          </div>
        </div>
      </footer>

      {/* Back to top */}
      {scrolled && (
        <button
          onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
          className="fixed bottom-6 right-6 w-10 h-10 bg-blue-600 hover:bg-blue-500 text-white rounded-full shadow-lg flex items-center justify-center transition-colors z-50"
        >
          <ChevronUp className="w-4 h-4" />
        </button>
      )}
    </div>
  );
}
